package com.yunyi.dao.wong_user;

import java.util.List;

import com.yunyi.domain.wong_user.RoleResource;
import com.yunyi.domain.wong_user.RoleResourceExample;
import org.apache.ibatis.annotations.Param;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Wed Jan 16 15:35:01 CST 2019
     */
    int countByExample(RoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Wed Jan 16 15:35:01 CST 2019
     */
    int deleteByExample(RoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Wed Jan 16 15:35:01 CST 2019
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Wed Jan 16 15:35:01 CST 2019
     */
    int insertSelective(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Wed Jan 16 15:35:01 CST 2019
     */
    List<RoleResource> selectByExample(RoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Wed Jan 16 15:35:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleResource record, @Param("example") RoleResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_resource
     *
     * @mbggenerated Wed Jan 16 15:35:01 CST 2019
     */
    int updateByExample(@Param("record") RoleResource record, @Param("example") RoleResourceExample example);
}