package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.Accounts;
import org.yunyisite.domain.AccountsExample;

public interface AccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int countByExample(AccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByExample(AccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insert(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insertSelective(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    List<Accounts> selectByExample(AccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    Accounts selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Accounts record, @Param("example") AccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExample(@Param("record") Accounts record, @Param("example") AccountsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKeySelective(Accounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Accounts
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKey(Accounts record);
}