package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.Contactors;
import org.yunyisite.domain.ContactorsExample;

public interface ContactorsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int countByExample(ContactorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByExample(ContactorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insert(Contactors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insertSelective(Contactors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    List<Contactors> selectByExample(ContactorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    Contactors selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Contactors record, @Param("example") ContactorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExample(@Param("record") Contactors record, @Param("example") ContactorsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKeySelective(Contactors record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Contactors
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKey(Contactors record);
}