package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.Customerloginlogs;
import org.yunyisite.domain.CustomerloginlogsExample;

public interface CustomerloginlogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int countByExample(CustomerloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByExample(CustomerloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insert(Customerloginlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insertSelective(Customerloginlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    List<Customerloginlogs> selectByExample(CustomerloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    Customerloginlogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") Customerloginlogs record, @Param("example") CustomerloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExample(@Param("record") Customerloginlogs record, @Param("example") CustomerloginlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKeySelective(Customerloginlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CustomerLoginLogs
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKey(Customerloginlogs record);
}