package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.Notice;
import org.yunyisite.domain.NoticeExample;
import org.yunyisite.domain.NoticeWithBLOBs;
import org.yunyisite.dto.NoticeDTO;

public interface NoticeMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int countByExample(NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int deleteByExample(NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int insert(NoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int insertSelective(NoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	List<NoticeWithBLOBs> selectByExampleWithBLOBs(NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	List<Notice> selectByExample(NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	NoticeWithBLOBs selectByPrimaryKey(String id);

	/**
	 * 公告查询(联查关联的业务系统)
	 * 
	 * @param id
	 * @return
	 */
	NoticeDTO selectExtendByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByExampleSelective(@Param("record") NoticeWithBLOBs record, @Param("example") NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") NoticeWithBLOBs record, @Param("example") NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByPrimaryKeySelective(NoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(NoticeWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Notice
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByPrimaryKey(Notice record);

	int updateById(String Id, String title, String content);
}