package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.ReCustomerContactorBusinesssystem;
import org.yunyisite.domain.ReCustomerContactorBusinesssystemExample;
import org.yunyisite.domain.ReCustomerContactorBusinesssystemKey;

public interface ReCustomerContactorBusinesssystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int countByExample(ReCustomerContactorBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByExample(ReCustomerContactorBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByPrimaryKey(ReCustomerContactorBusinesssystemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insert(ReCustomerContactorBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insertSelective(ReCustomerContactorBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    List<ReCustomerContactorBusinesssystem> selectByExample(ReCustomerContactorBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    ReCustomerContactorBusinesssystem selectByPrimaryKey(ReCustomerContactorBusinesssystemKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReCustomerContactorBusinesssystem record, @Param("example") ReCustomerContactorBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExample(@Param("record") ReCustomerContactorBusinesssystem record, @Param("example") ReCustomerContactorBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKeySelective(ReCustomerContactorBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Customer_Contactor_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKey(ReCustomerContactorBusinesssystem record);
}