package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.ReNoticeBusinesssystem;
import org.yunyisite.domain.ReNoticeBusinesssystemExample;
import org.yunyisite.dto.ReNoticeBusinesssystemDTO;

public interface ReNoticeBusinesssystemMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int countByExample(ReNoticeBusinesssystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int deleteByExample(ReNoticeBusinesssystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int insert(ReNoticeBusinesssystem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int insertSelective(ReNoticeBusinesssystem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	List<ReNoticeBusinesssystem> selectByExample(ReNoticeBusinesssystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	ReNoticeBusinesssystem selectByPrimaryKey(String id);

	/**
	 * 根据公告Id查询(联查业务系统)
	 * 
	 * @param noticeId
	 * @return
	 */
	ReNoticeBusinesssystemDTO selectByNoticeId(String noticeId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ReNoticeBusinesssystem record,
			@Param("example") ReNoticeBusinesssystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByExample(@Param("record") ReNoticeBusinesssystem record,
			@Param("example") ReNoticeBusinesssystemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByPrimaryKeySelective(ReNoticeBusinesssystem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table Re_Notice_BusinessSystem
	 *
	 * @mbggenerated Mon Dec 18 16:24:35 CST 2017
	 */
	int updateByPrimaryKey(ReNoticeBusinesssystem record);
}