package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.ReNoticeContactor;
import org.yunyisite.domain.ReNoticeContactorExample;

public interface ReNoticeContactorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int countByExample(ReNoticeContactorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByExample(ReNoticeContactorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insert(ReNoticeContactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insertSelective(ReNoticeContactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    List<ReNoticeContactor> selectByExample(ReNoticeContactorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    ReNoticeContactor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReNoticeContactor record, @Param("example") ReNoticeContactorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExample(@Param("record") ReNoticeContactor record, @Param("example") ReNoticeContactorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKeySelective(ReNoticeContactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKey(ReNoticeContactor record);
}