package org.yunyisite.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yunyisite.domain.ReResourceBusinesssystem;
import org.yunyisite.domain.ReResourceBusinesssystemExample;

public interface ReResourceBusinesssystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int countByExample(ReResourceBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByExample(ReResourceBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insert(ReResourceBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int insertSelective(ReResourceBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    List<ReResourceBusinesssystem> selectByExample(ReResourceBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    ReResourceBusinesssystem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") ReResourceBusinesssystem record, @Param("example") ReResourceBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByExample(@Param("record") ReResourceBusinesssystem record, @Param("example") ReResourceBusinesssystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKeySelective(ReResourceBusinesssystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Resource_BusinessSystem
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    int updateByPrimaryKey(ReResourceBusinesssystem record);
}