package org.yoong.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.yoong.domain.Resource;
import org.yoong.domain.ResourceExample;

public interface ResourceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	long countByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int deleteByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int insert(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int insertSelective(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	List<Resource> selectByExample(ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	Resource selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int updateByExample(@Param("record") Resource record, @Param("example") ResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int updateByPrimaryKeySelective(Resource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table resource
	 * @mbg.generated  Wed Aug 22 19:53:40 CST 2018
	 */
	int updateByPrimaryKey(Resource record);
}