package org.yunyisite.domain;

import java.util.Date;

public class Businesssystem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemmstsynno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.BusinessSystemFullName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemfullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.BeforeBusinessId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String beforebusinessid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.BeforeBusinessName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String beforebusinessname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.Status
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.UpdateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.ProductId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.ServiceUserNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String serviceuserno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.ServiceUserName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String serviceusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.MaintainCommissionerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String maintaincommissionerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BusinessSystem.MaintainCommissionerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String maintaincommissionername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.Id
     *
     * @return the value of BusinessSystem.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.Id
     *
     * @param id the value for BusinessSystem.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.BusinessSystemNo
     *
     * @return the value of BusinessSystem.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemno() {
        return businesssystemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.BusinessSystemNo
     *
     * @param businesssystemno the value for BusinessSystem.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemno(String businesssystemno) {
        this.businesssystemno = businesssystemno == null ? null : businesssystemno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.BusinessSystemMstSynNo
     *
     * @return the value of BusinessSystem.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemmstsynno() {
        return businesssystemmstsynno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.BusinessSystemMstSynNo
     *
     * @param businesssystemmstsynno the value for BusinessSystem.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemmstsynno(String businesssystemmstsynno) {
        this.businesssystemmstsynno = businesssystemmstsynno == null ? null : businesssystemmstsynno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.BusinessSystemName
     *
     * @return the value of BusinessSystem.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemname() {
        return businesssystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.BusinessSystemName
     *
     * @param businesssystemname the value for BusinessSystem.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemname(String businesssystemname) {
        this.businesssystemname = businesssystemname == null ? null : businesssystemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.BusinessSystemFullName
     *
     * @return the value of BusinessSystem.BusinessSystemFullName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemfullname() {
        return businesssystemfullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.BusinessSystemFullName
     *
     * @param businesssystemfullname the value for BusinessSystem.BusinessSystemFullName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemfullname(String businesssystemfullname) {
        this.businesssystemfullname = businesssystemfullname == null ? null : businesssystemfullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.BeforeBusinessId
     *
     * @return the value of BusinessSystem.BeforeBusinessId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBeforebusinessid() {
        return beforebusinessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.BeforeBusinessId
     *
     * @param beforebusinessid the value for BusinessSystem.BeforeBusinessId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBeforebusinessid(String beforebusinessid) {
        this.beforebusinessid = beforebusinessid == null ? null : beforebusinessid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.BeforeBusinessName
     *
     * @return the value of BusinessSystem.BeforeBusinessName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBeforebusinessname() {
        return beforebusinessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.BeforeBusinessName
     *
     * @param beforebusinessname the value for BusinessSystem.BeforeBusinessName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBeforebusinessname(String beforebusinessname) {
        this.beforebusinessname = beforebusinessname == null ? null : beforebusinessname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.Status
     *
     * @return the value of BusinessSystem.Status
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.Status
     *
     * @param status the value for BusinessSystem.Status
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.UpdateTime
     *
     * @return the value of BusinessSystem.UpdateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.UpdateTime
     *
     * @param updatetime the value for BusinessSystem.UpdateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.ProductId
     *
     * @return the value of BusinessSystem.ProductId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.ProductId
     *
     * @param productid the value for BusinessSystem.ProductId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.ServiceUserNo
     *
     * @return the value of BusinessSystem.ServiceUserNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getServiceuserno() {
        return serviceuserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.ServiceUserNo
     *
     * @param serviceuserno the value for BusinessSystem.ServiceUserNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setServiceuserno(String serviceuserno) {
        this.serviceuserno = serviceuserno == null ? null : serviceuserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.ServiceUserName
     *
     * @return the value of BusinessSystem.ServiceUserName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getServiceusername() {
        return serviceusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.ServiceUserName
     *
     * @param serviceusername the value for BusinessSystem.ServiceUserName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setServiceusername(String serviceusername) {
        this.serviceusername = serviceusername == null ? null : serviceusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.Definition1
     *
     * @return the value of BusinessSystem.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition1() {
        return definition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.Definition1
     *
     * @param definition1 the value for BusinessSystem.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition1(String definition1) {
        this.definition1 = definition1 == null ? null : definition1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.Definition2
     *
     * @return the value of BusinessSystem.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition2() {
        return definition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.Definition2
     *
     * @param definition2 the value for BusinessSystem.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition2(String definition2) {
        this.definition2 = definition2 == null ? null : definition2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.IsDelete
     *
     * @return the value of BusinessSystem.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.IsDelete
     *
     * @param isdelete the value for BusinessSystem.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.MaintainCommissionerNo
     *
     * @return the value of BusinessSystem.MaintainCommissionerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getMaintaincommissionerno() {
        return maintaincommissionerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.MaintainCommissionerNo
     *
     * @param maintaincommissionerno the value for BusinessSystem.MaintainCommissionerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setMaintaincommissionerno(String maintaincommissionerno) {
        this.maintaincommissionerno = maintaincommissionerno == null ? null : maintaincommissionerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BusinessSystem.MaintainCommissionerName
     *
     * @return the value of BusinessSystem.MaintainCommissionerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getMaintaincommissionername() {
        return maintaincommissionername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BusinessSystem.MaintainCommissionerName
     *
     * @param maintaincommissionername the value for BusinessSystem.MaintainCommissionerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setMaintaincommissionername(String maintaincommissionername) {
        this.maintaincommissionername = maintaincommissionername == null ? null : maintaincommissionername.trim();
    }
}