package org.yunyisite.domain;

import java.util.Date;

public class Contactors {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerStaffName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerstaffname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.Department
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.Job
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerStaffPhone
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerstaffphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerStaffFax
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerstafffax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerStaffMobile
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerstaffmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerStaffEmail
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerstaffemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerStaffAddress
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerstaffaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.CustomerStaffActiveStatusName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerstaffactivestatusname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.UpdateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Contactors.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.Id
     *
     * @return the value of Contactors.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.Id
     *
     * @param id the value for Contactors.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerStaffName
     *
     * @return the value of Contactors.CustomerStaffName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerstaffname() {
        return customerstaffname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerStaffName
     *
     * @param customerstaffname the value for Contactors.CustomerStaffName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerstaffname(String customerstaffname) {
        this.customerstaffname = customerstaffname == null ? null : customerstaffname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerId
     *
     * @return the value of Contactors.CustomerId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerId
     *
     * @param customerid the value for Contactors.CustomerId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerNo
     *
     * @return the value of Contactors.CustomerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerNo
     *
     * @param customerno the value for Contactors.CustomerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerName
     *
     * @return the value of Contactors.CustomerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerName
     *
     * @param customername the value for Contactors.CustomerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.Department
     *
     * @return the value of Contactors.Department
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.Department
     *
     * @param department the value for Contactors.Department
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.Job
     *
     * @return the value of Contactors.Job
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.Job
     *
     * @param job the value for Contactors.Job
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerStaffPhone
     *
     * @return the value of Contactors.CustomerStaffPhone
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerstaffphone() {
        return customerstaffphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerStaffPhone
     *
     * @param customerstaffphone the value for Contactors.CustomerStaffPhone
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerstaffphone(String customerstaffphone) {
        this.customerstaffphone = customerstaffphone == null ? null : customerstaffphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerStaffFax
     *
     * @return the value of Contactors.CustomerStaffFax
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerstafffax() {
        return customerstafffax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerStaffFax
     *
     * @param customerstafffax the value for Contactors.CustomerStaffFax
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerstafffax(String customerstafffax) {
        this.customerstafffax = customerstafffax == null ? null : customerstafffax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerStaffMobile
     *
     * @return the value of Contactors.CustomerStaffMobile
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerstaffmobile() {
        return customerstaffmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerStaffMobile
     *
     * @param customerstaffmobile the value for Contactors.CustomerStaffMobile
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerstaffmobile(String customerstaffmobile) {
        this.customerstaffmobile = customerstaffmobile == null ? null : customerstaffmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerStaffEmail
     *
     * @return the value of Contactors.CustomerStaffEmail
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerstaffemail() {
        return customerstaffemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerStaffEmail
     *
     * @param customerstaffemail the value for Contactors.CustomerStaffEmail
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerstaffemail(String customerstaffemail) {
        this.customerstaffemail = customerstaffemail == null ? null : customerstaffemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerStaffAddress
     *
     * @return the value of Contactors.CustomerStaffAddress
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerstaffaddress() {
        return customerstaffaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerStaffAddress
     *
     * @param customerstaffaddress the value for Contactors.CustomerStaffAddress
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerstaffaddress(String customerstaffaddress) {
        this.customerstaffaddress = customerstaffaddress == null ? null : customerstaffaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.CustomerStaffActiveStatusName
     *
     * @return the value of Contactors.CustomerStaffActiveStatusName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerstaffactivestatusname() {
        return customerstaffactivestatusname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.CustomerStaffActiveStatusName
     *
     * @param customerstaffactivestatusname the value for Contactors.CustomerStaffActiveStatusName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerstaffactivestatusname(String customerstaffactivestatusname) {
        this.customerstaffactivestatusname = customerstaffactivestatusname == null ? null : customerstaffactivestatusname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.UpdateTime
     *
     * @return the value of Contactors.UpdateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.UpdateTime
     *
     * @param updatetime the value for Contactors.UpdateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.Definition1
     *
     * @return the value of Contactors.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition1() {
        return definition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.Definition1
     *
     * @param definition1 the value for Contactors.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition1(String definition1) {
        this.definition1 = definition1 == null ? null : definition1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.Definition2
     *
     * @return the value of Contactors.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition2() {
        return definition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.Definition2
     *
     * @param definition2 the value for Contactors.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition2(String definition2) {
        this.definition2 = definition2 == null ? null : definition2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Contactors.IsDelete
     *
     * @return the value of Contactors.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Contactors.IsDelete
     *
     * @param isdelete the value for Contactors.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}