package org.yunyisite.domain;

import java.util.Date;

public class Questionaires {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.Name
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.QuestionCount
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Integer questioncount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.Creator
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.CreateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Boolean isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.DeleteTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Date deletetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Questionaires.Link
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String link;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.Id
     *
     * @return the value of Questionaires.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.Id
     *
     * @param id the value for Questionaires.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.Name
     *
     * @return the value of Questionaires.Name
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.Name
     *
     * @param name the value for Questionaires.Name
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.QuestionCount
     *
     * @return the value of Questionaires.QuestionCount
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Integer getQuestioncount() {
        return questioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.QuestionCount
     *
     * @param questioncount the value for Questionaires.QuestionCount
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setQuestioncount(Integer questioncount) {
        this.questioncount = questioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.Creator
     *
     * @return the value of Questionaires.Creator
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.Creator
     *
     * @param creator the value for Questionaires.Creator
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.CreateTime
     *
     * @return the value of Questionaires.CreateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.CreateTime
     *
     * @param createtime the value for Questionaires.CreateTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.IsDelete
     *
     * @return the value of Questionaires.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.IsDelete
     *
     * @param isdelete the value for Questionaires.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.DeleteTime
     *
     * @return the value of Questionaires.DeleteTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Date getDeletetime() {
        return deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.DeleteTime
     *
     * @param deletetime the value for Questionaires.DeleteTime
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDeletetime(Date deletetime) {
        this.deletetime = deletetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.Definition1
     *
     * @return the value of Questionaires.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition1() {
        return definition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.Definition1
     *
     * @param definition1 the value for Questionaires.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition1(String definition1) {
        this.definition1 = definition1 == null ? null : definition1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.Definition2
     *
     * @return the value of Questionaires.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition2() {
        return definition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.Definition2
     *
     * @param definition2 the value for Questionaires.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition2(String definition2) {
        this.definition2 = definition2 == null ? null : definition2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Questionaires.Link
     *
     * @return the value of Questionaires.Link
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Questionaires.Link
     *
     * @param link the value for Questionaires.Link
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }
}