package org.yunyisite.domain;

import java.util.ArrayList;
import java.util.List;

public class ReNoticeContactorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public ReNoticeContactorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("Id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("Id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNoticeidIsNull() {
            addCriterion("NoticeId is null");
            return (Criteria) this;
        }

        public Criteria andNoticeidIsNotNull() {
            addCriterion("NoticeId is not null");
            return (Criteria) this;
        }

        public Criteria andNoticeidEqualTo(String value) {
            addCriterion("NoticeId =", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidNotEqualTo(String value) {
            addCriterion("NoticeId <>", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidGreaterThan(String value) {
            addCriterion("NoticeId >", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidGreaterThanOrEqualTo(String value) {
            addCriterion("NoticeId >=", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidLessThan(String value) {
            addCriterion("NoticeId <", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidLessThanOrEqualTo(String value) {
            addCriterion("NoticeId <=", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidLike(String value) {
            addCriterion("NoticeId like", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidNotLike(String value) {
            addCriterion("NoticeId not like", value, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidIn(List<String> values) {
            addCriterion("NoticeId in", values, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidNotIn(List<String> values) {
            addCriterion("NoticeId not in", values, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidBetween(String value1, String value2) {
            addCriterion("NoticeId between", value1, value2, "noticeid");
            return (Criteria) this;
        }

        public Criteria andNoticeidNotBetween(String value1, String value2) {
            addCriterion("NoticeId not between", value1, value2, "noticeid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidIsNull() {
            addCriterion("CustomerStaffId is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidIsNotNull() {
            addCriterion("CustomerStaffId is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidEqualTo(String value) {
            addCriterion("CustomerStaffId =", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidNotEqualTo(String value) {
            addCriterion("CustomerStaffId <>", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidGreaterThan(String value) {
            addCriterion("CustomerStaffId >", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerStaffId >=", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidLessThan(String value) {
            addCriterion("CustomerStaffId <", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidLessThanOrEqualTo(String value) {
            addCriterion("CustomerStaffId <=", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidLike(String value) {
            addCriterion("CustomerStaffId like", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidNotLike(String value) {
            addCriterion("CustomerStaffId not like", value, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidIn(List<String> values) {
            addCriterion("CustomerStaffId in", values, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidNotIn(List<String> values) {
            addCriterion("CustomerStaffId not in", values, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidBetween(String value1, String value2) {
            addCriterion("CustomerStaffId between", value1, value2, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffidNotBetween(String value1, String value2) {
            addCriterion("CustomerStaffId not between", value1, value2, "customerstaffid");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameIsNull() {
            addCriterion("CustomerStaffName is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameIsNotNull() {
            addCriterion("CustomerStaffName is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameEqualTo(String value) {
            addCriterion("CustomerStaffName =", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameNotEqualTo(String value) {
            addCriterion("CustomerStaffName <>", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameGreaterThan(String value) {
            addCriterion("CustomerStaffName >", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerStaffName >=", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameLessThan(String value) {
            addCriterion("CustomerStaffName <", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameLessThanOrEqualTo(String value) {
            addCriterion("CustomerStaffName <=", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameLike(String value) {
            addCriterion("CustomerStaffName like", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameNotLike(String value) {
            addCriterion("CustomerStaffName not like", value, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameIn(List<String> values) {
            addCriterion("CustomerStaffName in", values, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameNotIn(List<String> values) {
            addCriterion("CustomerStaffName not in", values, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameBetween(String value1, String value2) {
            addCriterion("CustomerStaffName between", value1, value2, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffnameNotBetween(String value1, String value2) {
            addCriterion("CustomerStaffName not between", value1, value2, "customerstaffname");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneIsNull() {
            addCriterion("CustomerStaffPhone is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneIsNotNull() {
            addCriterion("CustomerStaffPhone is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneEqualTo(String value) {
            addCriterion("CustomerStaffPhone =", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneNotEqualTo(String value) {
            addCriterion("CustomerStaffPhone <>", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneGreaterThan(String value) {
            addCriterion("CustomerStaffPhone >", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerStaffPhone >=", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneLessThan(String value) {
            addCriterion("CustomerStaffPhone <", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneLessThanOrEqualTo(String value) {
            addCriterion("CustomerStaffPhone <=", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneLike(String value) {
            addCriterion("CustomerStaffPhone like", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneNotLike(String value) {
            addCriterion("CustomerStaffPhone not like", value, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneIn(List<String> values) {
            addCriterion("CustomerStaffPhone in", values, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneNotIn(List<String> values) {
            addCriterion("CustomerStaffPhone not in", values, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneBetween(String value1, String value2) {
            addCriterion("CustomerStaffPhone between", value1, value2, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffphoneNotBetween(String value1, String value2) {
            addCriterion("CustomerStaffPhone not between", value1, value2, "customerstaffphone");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxIsNull() {
            addCriterion("CustomerStaffFax is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxIsNotNull() {
            addCriterion("CustomerStaffFax is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxEqualTo(String value) {
            addCriterion("CustomerStaffFax =", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxNotEqualTo(String value) {
            addCriterion("CustomerStaffFax <>", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxGreaterThan(String value) {
            addCriterion("CustomerStaffFax >", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerStaffFax >=", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxLessThan(String value) {
            addCriterion("CustomerStaffFax <", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxLessThanOrEqualTo(String value) {
            addCriterion("CustomerStaffFax <=", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxLike(String value) {
            addCriterion("CustomerStaffFax like", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxNotLike(String value) {
            addCriterion("CustomerStaffFax not like", value, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxIn(List<String> values) {
            addCriterion("CustomerStaffFax in", values, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxNotIn(List<String> values) {
            addCriterion("CustomerStaffFax not in", values, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxBetween(String value1, String value2) {
            addCriterion("CustomerStaffFax between", value1, value2, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstafffaxNotBetween(String value1, String value2) {
            addCriterion("CustomerStaffFax not between", value1, value2, "customerstafffax");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileIsNull() {
            addCriterion("CustomerStaffMobile is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileIsNotNull() {
            addCriterion("CustomerStaffMobile is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileEqualTo(String value) {
            addCriterion("CustomerStaffMobile =", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileNotEqualTo(String value) {
            addCriterion("CustomerStaffMobile <>", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileGreaterThan(String value) {
            addCriterion("CustomerStaffMobile >", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerStaffMobile >=", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileLessThan(String value) {
            addCriterion("CustomerStaffMobile <", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileLessThanOrEqualTo(String value) {
            addCriterion("CustomerStaffMobile <=", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileLike(String value) {
            addCriterion("CustomerStaffMobile like", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileNotLike(String value) {
            addCriterion("CustomerStaffMobile not like", value, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileIn(List<String> values) {
            addCriterion("CustomerStaffMobile in", values, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileNotIn(List<String> values) {
            addCriterion("CustomerStaffMobile not in", values, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileBetween(String value1, String value2) {
            addCriterion("CustomerStaffMobile between", value1, value2, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffmobileNotBetween(String value1, String value2) {
            addCriterion("CustomerStaffMobile not between", value1, value2, "customerstaffmobile");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailIsNull() {
            addCriterion("CustomerStaffEmail is null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailIsNotNull() {
            addCriterion("CustomerStaffEmail is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailEqualTo(String value) {
            addCriterion("CustomerStaffEmail =", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailNotEqualTo(String value) {
            addCriterion("CustomerStaffEmail <>", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailGreaterThan(String value) {
            addCriterion("CustomerStaffEmail >", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerStaffEmail >=", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailLessThan(String value) {
            addCriterion("CustomerStaffEmail <", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailLessThanOrEqualTo(String value) {
            addCriterion("CustomerStaffEmail <=", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailLike(String value) {
            addCriterion("CustomerStaffEmail like", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailNotLike(String value) {
            addCriterion("CustomerStaffEmail not like", value, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailIn(List<String> values) {
            addCriterion("CustomerStaffEmail in", values, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailNotIn(List<String> values) {
            addCriterion("CustomerStaffEmail not in", values, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailBetween(String value1, String value2) {
            addCriterion("CustomerStaffEmail between", value1, value2, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomerstaffemailNotBetween(String value1, String value2) {
            addCriterion("CustomerStaffEmail not between", value1, value2, "customerstaffemail");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNull() {
            addCriterion("CustomerId is null");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNotNull() {
            addCriterion("CustomerId is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeridEqualTo(String value) {
            addCriterion("CustomerId =", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotEqualTo(String value) {
            addCriterion("CustomerId <>", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThan(String value) {
            addCriterion("CustomerId >", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerId >=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThan(String value) {
            addCriterion("CustomerId <", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThanOrEqualTo(String value) {
            addCriterion("CustomerId <=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLike(String value) {
            addCriterion("CustomerId like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotLike(String value) {
            addCriterion("CustomerId not like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIn(List<String> values) {
            addCriterion("CustomerId in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotIn(List<String> values) {
            addCriterion("CustomerId not in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridBetween(String value1, String value2) {
            addCriterion("CustomerId between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotBetween(String value1, String value2) {
            addCriterion("CustomerId not between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomernoIsNull() {
            addCriterion("CustomerNo is null");
            return (Criteria) this;
        }

        public Criteria andCustomernoIsNotNull() {
            addCriterion("CustomerNo is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernoEqualTo(String value) {
            addCriterion("CustomerNo =", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotEqualTo(String value) {
            addCriterion("CustomerNo <>", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoGreaterThan(String value) {
            addCriterion("CustomerNo >", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerNo >=", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLessThan(String value) {
            addCriterion("CustomerNo <", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLessThanOrEqualTo(String value) {
            addCriterion("CustomerNo <=", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLike(String value) {
            addCriterion("CustomerNo like", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotLike(String value) {
            addCriterion("CustomerNo not like", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoIn(List<String> values) {
            addCriterion("CustomerNo in", values, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotIn(List<String> values) {
            addCriterion("CustomerNo not in", values, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoBetween(String value1, String value2) {
            addCriterion("CustomerNo between", value1, value2, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotBetween(String value1, String value2) {
            addCriterion("CustomerNo not between", value1, value2, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNull() {
            addCriterion("CustomerName is null");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNotNull() {
            addCriterion("CustomerName is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernameEqualTo(String value) {
            addCriterion("CustomerName =", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotEqualTo(String value) {
            addCriterion("CustomerName <>", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThan(String value) {
            addCriterion("CustomerName >", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerName >=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThan(String value) {
            addCriterion("CustomerName <", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThanOrEqualTo(String value) {
            addCriterion("CustomerName <=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLike(String value) {
            addCriterion("CustomerName like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotLike(String value) {
            addCriterion("CustomerName not like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameIn(List<String> values) {
            addCriterion("CustomerName in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotIn(List<String> values) {
            addCriterion("CustomerName not in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameBetween(String value1, String value2) {
            addCriterion("CustomerName between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotBetween(String value1, String value2) {
            addCriterion("CustomerName not between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidIsNull() {
            addCriterion("BusinessSystemId is null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidIsNotNull() {
            addCriterion("BusinessSystemId is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidEqualTo(String value) {
            addCriterion("BusinessSystemId =", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidNotEqualTo(String value) {
            addCriterion("BusinessSystemId <>", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidGreaterThan(String value) {
            addCriterion("BusinessSystemId >", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidGreaterThanOrEqualTo(String value) {
            addCriterion("BusinessSystemId >=", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidLessThan(String value) {
            addCriterion("BusinessSystemId <", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidLessThanOrEqualTo(String value) {
            addCriterion("BusinessSystemId <=", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidLike(String value) {
            addCriterion("BusinessSystemId like", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidNotLike(String value) {
            addCriterion("BusinessSystemId not like", value, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidIn(List<String> values) {
            addCriterion("BusinessSystemId in", values, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidNotIn(List<String> values) {
            addCriterion("BusinessSystemId not in", values, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidBetween(String value1, String value2) {
            addCriterion("BusinessSystemId between", value1, value2, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemidNotBetween(String value1, String value2) {
            addCriterion("BusinessSystemId not between", value1, value2, "businesssystemid");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoIsNull() {
            addCriterion("BusinessSystemNo is null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoIsNotNull() {
            addCriterion("BusinessSystemNo is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoEqualTo(String value) {
            addCriterion("BusinessSystemNo =", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoNotEqualTo(String value) {
            addCriterion("BusinessSystemNo <>", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoGreaterThan(String value) {
            addCriterion("BusinessSystemNo >", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoGreaterThanOrEqualTo(String value) {
            addCriterion("BusinessSystemNo >=", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoLessThan(String value) {
            addCriterion("BusinessSystemNo <", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoLessThanOrEqualTo(String value) {
            addCriterion("BusinessSystemNo <=", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoLike(String value) {
            addCriterion("BusinessSystemNo like", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoNotLike(String value) {
            addCriterion("BusinessSystemNo not like", value, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoIn(List<String> values) {
            addCriterion("BusinessSystemNo in", values, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoNotIn(List<String> values) {
            addCriterion("BusinessSystemNo not in", values, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoBetween(String value1, String value2) {
            addCriterion("BusinessSystemNo between", value1, value2, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnoNotBetween(String value1, String value2) {
            addCriterion("BusinessSystemNo not between", value1, value2, "businesssystemno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoIsNull() {
            addCriterion("BusinessSystemMstSynNo is null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoIsNotNull() {
            addCriterion("BusinessSystemMstSynNo is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoEqualTo(String value) {
            addCriterion("BusinessSystemMstSynNo =", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoNotEqualTo(String value) {
            addCriterion("BusinessSystemMstSynNo <>", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoGreaterThan(String value) {
            addCriterion("BusinessSystemMstSynNo >", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoGreaterThanOrEqualTo(String value) {
            addCriterion("BusinessSystemMstSynNo >=", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoLessThan(String value) {
            addCriterion("BusinessSystemMstSynNo <", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoLessThanOrEqualTo(String value) {
            addCriterion("BusinessSystemMstSynNo <=", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoLike(String value) {
            addCriterion("BusinessSystemMstSynNo like", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoNotLike(String value) {
            addCriterion("BusinessSystemMstSynNo not like", value, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoIn(List<String> values) {
            addCriterion("BusinessSystemMstSynNo in", values, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoNotIn(List<String> values) {
            addCriterion("BusinessSystemMstSynNo not in", values, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoBetween(String value1, String value2) {
            addCriterion("BusinessSystemMstSynNo between", value1, value2, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemmstsynnoNotBetween(String value1, String value2) {
            addCriterion("BusinessSystemMstSynNo not between", value1, value2, "businesssystemmstsynno");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameIsNull() {
            addCriterion("BusinessSystemName is null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameIsNotNull() {
            addCriterion("BusinessSystemName is not null");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameEqualTo(String value) {
            addCriterion("BusinessSystemName =", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameNotEqualTo(String value) {
            addCriterion("BusinessSystemName <>", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameGreaterThan(String value) {
            addCriterion("BusinessSystemName >", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameGreaterThanOrEqualTo(String value) {
            addCriterion("BusinessSystemName >=", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameLessThan(String value) {
            addCriterion("BusinessSystemName <", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameLessThanOrEqualTo(String value) {
            addCriterion("BusinessSystemName <=", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameLike(String value) {
            addCriterion("BusinessSystemName like", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameNotLike(String value) {
            addCriterion("BusinessSystemName not like", value, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameIn(List<String> values) {
            addCriterion("BusinessSystemName in", values, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameNotIn(List<String> values) {
            addCriterion("BusinessSystemName not in", values, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameBetween(String value1, String value2) {
            addCriterion("BusinessSystemName between", value1, value2, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andBusinesssystemnameNotBetween(String value1, String value2) {
            addCriterion("BusinessSystemName not between", value1, value2, "businesssystemname");
            return (Criteria) this;
        }

        public Criteria andDefinition1IsNull() {
            addCriterion("Definition1 is null");
            return (Criteria) this;
        }

        public Criteria andDefinition1IsNotNull() {
            addCriterion("Definition1 is not null");
            return (Criteria) this;
        }

        public Criteria andDefinition1EqualTo(String value) {
            addCriterion("Definition1 =", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotEqualTo(String value) {
            addCriterion("Definition1 <>", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1GreaterThan(String value) {
            addCriterion("Definition1 >", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1GreaterThanOrEqualTo(String value) {
            addCriterion("Definition1 >=", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1LessThan(String value) {
            addCriterion("Definition1 <", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1LessThanOrEqualTo(String value) {
            addCriterion("Definition1 <=", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1Like(String value) {
            addCriterion("Definition1 like", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotLike(String value) {
            addCriterion("Definition1 not like", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1In(List<String> values) {
            addCriterion("Definition1 in", values, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotIn(List<String> values) {
            addCriterion("Definition1 not in", values, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1Between(String value1, String value2) {
            addCriterion("Definition1 between", value1, value2, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotBetween(String value1, String value2) {
            addCriterion("Definition1 not between", value1, value2, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition2IsNull() {
            addCriterion("Definition2 is null");
            return (Criteria) this;
        }

        public Criteria andDefinition2IsNotNull() {
            addCriterion("Definition2 is not null");
            return (Criteria) this;
        }

        public Criteria andDefinition2EqualTo(String value) {
            addCriterion("Definition2 =", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotEqualTo(String value) {
            addCriterion("Definition2 <>", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2GreaterThan(String value) {
            addCriterion("Definition2 >", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2GreaterThanOrEqualTo(String value) {
            addCriterion("Definition2 >=", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2LessThan(String value) {
            addCriterion("Definition2 <", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2LessThanOrEqualTo(String value) {
            addCriterion("Definition2 <=", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2Like(String value) {
            addCriterion("Definition2 like", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotLike(String value) {
            addCriterion("Definition2 not like", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2In(List<String> values) {
            addCriterion("Definition2 in", values, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotIn(List<String> values) {
            addCriterion("Definition2 not in", values, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2Between(String value1, String value2) {
            addCriterion("Definition2 between", value1, value2, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotBetween(String value1, String value2) {
            addCriterion("Definition2 not between", value1, value2, "definition2");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("IsDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("IsDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Boolean value) {
            addCriterion("IsDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Boolean value) {
            addCriterion("IsDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Boolean value) {
            addCriterion("IsDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Boolean value) {
            addCriterion("IsDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("IsDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Boolean> values) {
            addCriterion("IsDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Boolean> values) {
            addCriterion("IsDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("IsDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 18 16:24:35 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Re_Notice_Contactor
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}