package org.yunyisite.domain;

public class ReNoticeCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.NoticeId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.BusinessSystemId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemmstsynno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.CustomerId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.CustomerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customerno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.CustomerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Notice_Customer.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.Id
     *
     * @return the value of Re_Notice_Customer.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.Id
     *
     * @param id the value for Re_Notice_Customer.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.NoticeId
     *
     * @return the value of Re_Notice_Customer.NoticeId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.NoticeId
     *
     * @param noticeid the value for Re_Notice_Customer.NoticeId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setNoticeid(String noticeid) {
        this.noticeid = noticeid == null ? null : noticeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.BusinessSystemId
     *
     * @return the value of Re_Notice_Customer.BusinessSystemId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemid() {
        return businesssystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.BusinessSystemId
     *
     * @param businesssystemid the value for Re_Notice_Customer.BusinessSystemId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemid(String businesssystemid) {
        this.businesssystemid = businesssystemid == null ? null : businesssystemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.BusinessSystemNo
     *
     * @return the value of Re_Notice_Customer.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemno() {
        return businesssystemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.BusinessSystemNo
     *
     * @param businesssystemno the value for Re_Notice_Customer.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemno(String businesssystemno) {
        this.businesssystemno = businesssystemno == null ? null : businesssystemno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.BusinessSystemMstSynNo
     *
     * @return the value of Re_Notice_Customer.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemmstsynno() {
        return businesssystemmstsynno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.BusinessSystemMstSynNo
     *
     * @param businesssystemmstsynno the value for Re_Notice_Customer.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemmstsynno(String businesssystemmstsynno) {
        this.businesssystemmstsynno = businesssystemmstsynno == null ? null : businesssystemmstsynno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.BusinessSystemName
     *
     * @return the value of Re_Notice_Customer.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemname() {
        return businesssystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.BusinessSystemName
     *
     * @param businesssystemname the value for Re_Notice_Customer.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemname(String businesssystemname) {
        this.businesssystemname = businesssystemname == null ? null : businesssystemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.CustomerId
     *
     * @return the value of Re_Notice_Customer.CustomerId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.CustomerId
     *
     * @param customerid the value for Re_Notice_Customer.CustomerId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.CustomerNo
     *
     * @return the value of Re_Notice_Customer.CustomerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomerno() {
        return customerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.CustomerNo
     *
     * @param customerno the value for Re_Notice_Customer.CustomerNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomerno(String customerno) {
        this.customerno = customerno == null ? null : customerno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.CustomerName
     *
     * @return the value of Re_Notice_Customer.CustomerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.CustomerName
     *
     * @param customername the value for Re_Notice_Customer.CustomerName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.Definition1
     *
     * @return the value of Re_Notice_Customer.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition1() {
        return definition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.Definition1
     *
     * @param definition1 the value for Re_Notice_Customer.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition1(String definition1) {
        this.definition1 = definition1 == null ? null : definition1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.Definition2
     *
     * @return the value of Re_Notice_Customer.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition2() {
        return definition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.Definition2
     *
     * @param definition2 the value for Re_Notice_Customer.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition2(String definition2) {
        this.definition2 = definition2 == null ? null : definition2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Notice_Customer.IsDelete
     *
     * @return the value of Re_Notice_Customer.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Notice_Customer.IsDelete
     *
     * @param isdelete the value for Re_Notice_Customer.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}