package org.yunyisite.domain;

public class RequirementinsertparamsWithBLOBs extends Requirementinsertparams {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RequirementInsertParams.Description
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RequirementInsertParams.Memo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String memo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RequirementInsertParams.Description
     *
     * @return the value of RequirementInsertParams.Description
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RequirementInsertParams.Description
     *
     * @param description the value for RequirementInsertParams.Description
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RequirementInsertParams.Memo
     *
     * @return the value of RequirementInsertParams.Memo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RequirementInsertParams.Memo
     *
     * @param memo the value for RequirementInsertParams.Memo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }
}