package org.yunyisite.domain;

public class ReResourceBusinesssystem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.ResourceId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String resourceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.BusinessSystemId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemmstsynno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String businesssystemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String definition2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Re_Resource_BusinessSystem.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.Id
     *
     * @return the value of Re_Resource_BusinessSystem.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.Id
     *
     * @param id the value for Re_Resource_BusinessSystem.Id
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.ResourceId
     *
     * @return the value of Re_Resource_BusinessSystem.ResourceId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getResourceid() {
        return resourceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.ResourceId
     *
     * @param resourceid the value for Re_Resource_BusinessSystem.ResourceId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setResourceid(String resourceid) {
        this.resourceid = resourceid == null ? null : resourceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.BusinessSystemId
     *
     * @return the value of Re_Resource_BusinessSystem.BusinessSystemId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemid() {
        return businesssystemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.BusinessSystemId
     *
     * @param businesssystemid the value for Re_Resource_BusinessSystem.BusinessSystemId
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemid(String businesssystemid) {
        this.businesssystemid = businesssystemid == null ? null : businesssystemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.BusinessSystemNo
     *
     * @return the value of Re_Resource_BusinessSystem.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemno() {
        return businesssystemno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.BusinessSystemNo
     *
     * @param businesssystemno the value for Re_Resource_BusinessSystem.BusinessSystemNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemno(String businesssystemno) {
        this.businesssystemno = businesssystemno == null ? null : businesssystemno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.BusinessSystemMstSynNo
     *
     * @return the value of Re_Resource_BusinessSystem.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemmstsynno() {
        return businesssystemmstsynno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.BusinessSystemMstSynNo
     *
     * @param businesssystemmstsynno the value for Re_Resource_BusinessSystem.BusinessSystemMstSynNo
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemmstsynno(String businesssystemmstsynno) {
        this.businesssystemmstsynno = businesssystemmstsynno == null ? null : businesssystemmstsynno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.BusinessSystemName
     *
     * @return the value of Re_Resource_BusinessSystem.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getBusinesssystemname() {
        return businesssystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.BusinessSystemName
     *
     * @param businesssystemname the value for Re_Resource_BusinessSystem.BusinessSystemName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setBusinesssystemname(String businesssystemname) {
        this.businesssystemname = businesssystemname == null ? null : businesssystemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.Definition1
     *
     * @return the value of Re_Resource_BusinessSystem.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition1() {
        return definition1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.Definition1
     *
     * @param definition1 the value for Re_Resource_BusinessSystem.Definition1
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition1(String definition1) {
        this.definition1 = definition1 == null ? null : definition1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.Definition2
     *
     * @return the value of Re_Resource_BusinessSystem.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getDefinition2() {
        return definition2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.Definition2
     *
     * @param definition2 the value for Re_Resource_BusinessSystem.Definition2
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDefinition2(String definition2) {
        this.definition2 = definition2 == null ? null : definition2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Re_Resource_BusinessSystem.IsDelete
     *
     * @return the value of Re_Resource_BusinessSystem.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Re_Resource_BusinessSystem.IsDelete
     *
     * @param isdelete the value for Re_Resource_BusinessSystem.IsDelete
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}