package org.yunyisite.domain;

public class Resaletechproducts extends ResaletechproductsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ReSaleTechProducts.TechProductName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    private String techproductname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ReSaleTechProducts.TechProductName
     *
     * @return the value of ReSaleTechProducts.TechProductName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getTechproductname() {
        return techproductname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ReSaleTechProducts.TechProductName
     *
     * @param techproductname the value for ReSaleTechProducts.TechProductName
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setTechproductname(String techproductname) {
        this.techproductname = techproductname == null ? null : techproductname.trim();
    }
}