package org.yunyisite.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ResourceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public ResourceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("Id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("Id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("Title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("Title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("Title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("Title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("Title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("Title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("Title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("Title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("Title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("Title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("Title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("Title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("Title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("Title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("Type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("Type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("Type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("Type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("Type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("Type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("Type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("Type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("Type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("Type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("Type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("Type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("Type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("Type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andSubtypeIsNull() {
            addCriterion("SubType is null");
            return (Criteria) this;
        }

        public Criteria andSubtypeIsNotNull() {
            addCriterion("SubType is not null");
            return (Criteria) this;
        }

        public Criteria andSubtypeEqualTo(String value) {
            addCriterion("SubType =", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotEqualTo(String value) {
            addCriterion("SubType <>", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeGreaterThan(String value) {
            addCriterion("SubType >", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeGreaterThanOrEqualTo(String value) {
            addCriterion("SubType >=", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeLessThan(String value) {
            addCriterion("SubType <", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeLessThanOrEqualTo(String value) {
            addCriterion("SubType <=", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeLike(String value) {
            addCriterion("SubType like", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotLike(String value) {
            addCriterion("SubType not like", value, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeIn(List<String> values) {
            addCriterion("SubType in", values, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotIn(List<String> values) {
            addCriterion("SubType not in", values, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeBetween(String value1, String value2) {
            addCriterion("SubType between", value1, value2, "subtype");
            return (Criteria) this;
        }

        public Criteria andSubtypeNotBetween(String value1, String value2) {
            addCriterion("SubType not between", value1, value2, "subtype");
            return (Criteria) this;
        }

        public Criteria andAttachidIsNull() {
            addCriterion("AttachId is null");
            return (Criteria) this;
        }

        public Criteria andAttachidIsNotNull() {
            addCriterion("AttachId is not null");
            return (Criteria) this;
        }

        public Criteria andAttachidEqualTo(String value) {
            addCriterion("AttachId =", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidNotEqualTo(String value) {
            addCriterion("AttachId <>", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidGreaterThan(String value) {
            addCriterion("AttachId >", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidGreaterThanOrEqualTo(String value) {
            addCriterion("AttachId >=", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidLessThan(String value) {
            addCriterion("AttachId <", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidLessThanOrEqualTo(String value) {
            addCriterion("AttachId <=", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidLike(String value) {
            addCriterion("AttachId like", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidNotLike(String value) {
            addCriterion("AttachId not like", value, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidIn(List<String> values) {
            addCriterion("AttachId in", values, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidNotIn(List<String> values) {
            addCriterion("AttachId not in", values, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidBetween(String value1, String value2) {
            addCriterion("AttachId between", value1, value2, "attachid");
            return (Criteria) this;
        }

        public Criteria andAttachidNotBetween(String value1, String value2) {
            addCriterion("AttachId not between", value1, value2, "attachid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNull() {
            addCriterion("CustomerId is null");
            return (Criteria) this;
        }

        public Criteria andCustomeridIsNotNull() {
            addCriterion("CustomerId is not null");
            return (Criteria) this;
        }

        public Criteria andCustomeridEqualTo(String value) {
            addCriterion("CustomerId =", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotEqualTo(String value) {
            addCriterion("CustomerId <>", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThan(String value) {
            addCriterion("CustomerId >", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerId >=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThan(String value) {
            addCriterion("CustomerId <", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLessThanOrEqualTo(String value) {
            addCriterion("CustomerId <=", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridLike(String value) {
            addCriterion("CustomerId like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotLike(String value) {
            addCriterion("CustomerId not like", value, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridIn(List<String> values) {
            addCriterion("CustomerId in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotIn(List<String> values) {
            addCriterion("CustomerId not in", values, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridBetween(String value1, String value2) {
            addCriterion("CustomerId between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomeridNotBetween(String value1, String value2) {
            addCriterion("CustomerId not between", value1, value2, "customerid");
            return (Criteria) this;
        }

        public Criteria andCustomernoIsNull() {
            addCriterion("CustomerNo is null");
            return (Criteria) this;
        }

        public Criteria andCustomernoIsNotNull() {
            addCriterion("CustomerNo is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernoEqualTo(String value) {
            addCriterion("CustomerNo =", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotEqualTo(String value) {
            addCriterion("CustomerNo <>", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoGreaterThan(String value) {
            addCriterion("CustomerNo >", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerNo >=", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLessThan(String value) {
            addCriterion("CustomerNo <", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLessThanOrEqualTo(String value) {
            addCriterion("CustomerNo <=", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoLike(String value) {
            addCriterion("CustomerNo like", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotLike(String value) {
            addCriterion("CustomerNo not like", value, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoIn(List<String> values) {
            addCriterion("CustomerNo in", values, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotIn(List<String> values) {
            addCriterion("CustomerNo not in", values, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoBetween(String value1, String value2) {
            addCriterion("CustomerNo between", value1, value2, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernoNotBetween(String value1, String value2) {
            addCriterion("CustomerNo not between", value1, value2, "customerno");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNull() {
            addCriterion("CustomerName is null");
            return (Criteria) this;
        }

        public Criteria andCustomernameIsNotNull() {
            addCriterion("CustomerName is not null");
            return (Criteria) this;
        }

        public Criteria andCustomernameEqualTo(String value) {
            addCriterion("CustomerName =", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotEqualTo(String value) {
            addCriterion("CustomerName <>", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThan(String value) {
            addCriterion("CustomerName >", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameGreaterThanOrEqualTo(String value) {
            addCriterion("CustomerName >=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThan(String value) {
            addCriterion("CustomerName <", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLessThanOrEqualTo(String value) {
            addCriterion("CustomerName <=", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameLike(String value) {
            addCriterion("CustomerName like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotLike(String value) {
            addCriterion("CustomerName not like", value, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameIn(List<String> values) {
            addCriterion("CustomerName in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotIn(List<String> values) {
            addCriterion("CustomerName not in", values, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameBetween(String value1, String value2) {
            addCriterion("CustomerName between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCustomernameNotBetween(String value1, String value2) {
            addCriterion("CustomerName not between", value1, value2, "customername");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("Creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("Creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("Creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("Creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("Creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("Creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("Creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("Creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("Creator like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("Creator not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("Creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("Creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("Creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("Creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCoveridIsNull() {
            addCriterion("CoverId is null");
            return (Criteria) this;
        }

        public Criteria andCoveridIsNotNull() {
            addCriterion("CoverId is not null");
            return (Criteria) this;
        }

        public Criteria andCoveridEqualTo(String value) {
            addCriterion("CoverId =", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridNotEqualTo(String value) {
            addCriterion("CoverId <>", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridGreaterThan(String value) {
            addCriterion("CoverId >", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridGreaterThanOrEqualTo(String value) {
            addCriterion("CoverId >=", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridLessThan(String value) {
            addCriterion("CoverId <", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridLessThanOrEqualTo(String value) {
            addCriterion("CoverId <=", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridLike(String value) {
            addCriterion("CoverId like", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridNotLike(String value) {
            addCriterion("CoverId not like", value, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridIn(List<String> values) {
            addCriterion("CoverId in", values, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridNotIn(List<String> values) {
            addCriterion("CoverId not in", values, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridBetween(String value1, String value2) {
            addCriterion("CoverId between", value1, value2, "coverid");
            return (Criteria) this;
        }

        public Criteria andCoveridNotBetween(String value1, String value2) {
            addCriterion("CoverId not between", value1, value2, "coverid");
            return (Criteria) this;
        }

        public Criteria andCovernameIsNull() {
            addCriterion("CoverName is null");
            return (Criteria) this;
        }

        public Criteria andCovernameIsNotNull() {
            addCriterion("CoverName is not null");
            return (Criteria) this;
        }

        public Criteria andCovernameEqualTo(String value) {
            addCriterion("CoverName =", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameNotEqualTo(String value) {
            addCriterion("CoverName <>", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameGreaterThan(String value) {
            addCriterion("CoverName >", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameGreaterThanOrEqualTo(String value) {
            addCriterion("CoverName >=", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameLessThan(String value) {
            addCriterion("CoverName <", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameLessThanOrEqualTo(String value) {
            addCriterion("CoverName <=", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameLike(String value) {
            addCriterion("CoverName like", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameNotLike(String value) {
            addCriterion("CoverName not like", value, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameIn(List<String> values) {
            addCriterion("CoverName in", values, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameNotIn(List<String> values) {
            addCriterion("CoverName not in", values, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameBetween(String value1, String value2) {
            addCriterion("CoverName between", value1, value2, "covername");
            return (Criteria) this;
        }

        public Criteria andCovernameNotBetween(String value1, String value2) {
            addCriterion("CoverName not between", value1, value2, "covername");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationIsNull() {
            addCriterion("CoverStoreLocation is null");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationIsNotNull() {
            addCriterion("CoverStoreLocation is not null");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationEqualTo(String value) {
            addCriterion("CoverStoreLocation =", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationNotEqualTo(String value) {
            addCriterion("CoverStoreLocation <>", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationGreaterThan(String value) {
            addCriterion("CoverStoreLocation >", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationGreaterThanOrEqualTo(String value) {
            addCriterion("CoverStoreLocation >=", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationLessThan(String value) {
            addCriterion("CoverStoreLocation <", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationLessThanOrEqualTo(String value) {
            addCriterion("CoverStoreLocation <=", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationLike(String value) {
            addCriterion("CoverStoreLocation like", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationNotLike(String value) {
            addCriterion("CoverStoreLocation not like", value, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationIn(List<String> values) {
            addCriterion("CoverStoreLocation in", values, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationNotIn(List<String> values) {
            addCriterion("CoverStoreLocation not in", values, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationBetween(String value1, String value2) {
            addCriterion("CoverStoreLocation between", value1, value2, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andCoverstorelocationNotBetween(String value1, String value2) {
            addCriterion("CoverStoreLocation not between", value1, value2, "coverstorelocation");
            return (Criteria) this;
        }

        public Criteria andAttachsizeIsNull() {
            addCriterion("AttachSize is null");
            return (Criteria) this;
        }

        public Criteria andAttachsizeIsNotNull() {
            addCriterion("AttachSize is not null");
            return (Criteria) this;
        }

        public Criteria andAttachsizeEqualTo(Double value) {
            addCriterion("AttachSize =", value, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeNotEqualTo(Double value) {
            addCriterion("AttachSize <>", value, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeGreaterThan(Double value) {
            addCriterion("AttachSize >", value, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeGreaterThanOrEqualTo(Double value) {
            addCriterion("AttachSize >=", value, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeLessThan(Double value) {
            addCriterion("AttachSize <", value, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeLessThanOrEqualTo(Double value) {
            addCriterion("AttachSize <=", value, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeIn(List<Double> values) {
            addCriterion("AttachSize in", values, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeNotIn(List<Double> values) {
            addCriterion("AttachSize not in", values, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeBetween(Double value1, Double value2) {
            addCriterion("AttachSize between", value1, value2, "attachsize");
            return (Criteria) this;
        }

        public Criteria andAttachsizeNotBetween(Double value1, Double value2) {
            addCriterion("AttachSize not between", value1, value2, "attachsize");
            return (Criteria) this;
        }

        public Criteria andDefinition1IsNull() {
            addCriterion("Definition1 is null");
            return (Criteria) this;
        }

        public Criteria andDefinition1IsNotNull() {
            addCriterion("Definition1 is not null");
            return (Criteria) this;
        }

        public Criteria andDefinition1EqualTo(String value) {
            addCriterion("Definition1 =", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotEqualTo(String value) {
            addCriterion("Definition1 <>", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1GreaterThan(String value) {
            addCriterion("Definition1 >", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1GreaterThanOrEqualTo(String value) {
            addCriterion("Definition1 >=", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1LessThan(String value) {
            addCriterion("Definition1 <", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1LessThanOrEqualTo(String value) {
            addCriterion("Definition1 <=", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1Like(String value) {
            addCriterion("Definition1 like", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotLike(String value) {
            addCriterion("Definition1 not like", value, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1In(List<String> values) {
            addCriterion("Definition1 in", values, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotIn(List<String> values) {
            addCriterion("Definition1 not in", values, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1Between(String value1, String value2) {
            addCriterion("Definition1 between", value1, value2, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition1NotBetween(String value1, String value2) {
            addCriterion("Definition1 not between", value1, value2, "definition1");
            return (Criteria) this;
        }

        public Criteria andDefinition2IsNull() {
            addCriterion("Definition2 is null");
            return (Criteria) this;
        }

        public Criteria andDefinition2IsNotNull() {
            addCriterion("Definition2 is not null");
            return (Criteria) this;
        }

        public Criteria andDefinition2EqualTo(String value) {
            addCriterion("Definition2 =", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotEqualTo(String value) {
            addCriterion("Definition2 <>", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2GreaterThan(String value) {
            addCriterion("Definition2 >", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2GreaterThanOrEqualTo(String value) {
            addCriterion("Definition2 >=", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2LessThan(String value) {
            addCriterion("Definition2 <", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2LessThanOrEqualTo(String value) {
            addCriterion("Definition2 <=", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2Like(String value) {
            addCriterion("Definition2 like", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotLike(String value) {
            addCriterion("Definition2 not like", value, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2In(List<String> values) {
            addCriterion("Definition2 in", values, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotIn(List<String> values) {
            addCriterion("Definition2 not in", values, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2Between(String value1, String value2) {
            addCriterion("Definition2 between", value1, value2, "definition2");
            return (Criteria) this;
        }

        public Criteria andDefinition2NotBetween(String value1, String value2) {
            addCriterion("Definition2 not between", value1, value2, "definition2");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("IsDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("IsDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Boolean value) {
            addCriterion("IsDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Boolean value) {
            addCriterion("IsDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Boolean value) {
            addCriterion("IsDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Boolean value) {
            addCriterion("IsDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Boolean value) {
            addCriterion("IsDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Boolean value) {
            addCriterion("IsDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Boolean> values) {
            addCriterion("IsDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Boolean> values) {
            addCriterion("IsDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Boolean value1, Boolean value2) {
            addCriterion("IsDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Boolean value1, Boolean value2) {
            addCriterion("IsDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Resource
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 18 16:24:35 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Resource
     *
     * @mbggenerated Mon Dec 18 16:24:35 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}